server:
  port: 8090

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.0.100:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        request-timeout: 360s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-Gc4MRmuAk3Z13Jc89300C8E5051248A9Ae3bB1615c72A888
      chat:
        options:
          model: gpt-4o
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://c344591174e941a4b684-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml